### ISSUE TITLE
Toisto AIFF test suite results

### ISSUE THREAD

**Issue by karip** [AkiyukiOkayasu/pacmog#33]
I have written an [AIFF test suite](https://github.com/karip/toisto-aiff-test-suite) and I decided to try how pacmog can read the files in it.

Here's a summary of the results for pacmog:

 - it doesn't support 8 bit samples, so many test cases fail (unfortunately, I designed most test cases to use 8 bit samples..)
 - it doesn't seem to support SSND chunk before COMM or FVER chunks (the AIFF-C '91 spec says: "There are no restrictions on the ordering of local chunks within a FORM AIFC.")
 - it doesn't support uncompressed type "TWOS" in AIFC files (16-bit big-endian signed integer samples)
 - it panics if it is given a compression type that it doesn't support (should it return AudioFormat::Unknown??)
 - it doesn't seem to support offset and blocksize in the SSND chunk (those fields are rarely used so probably ok)
 - it doesn't return accurate values for 32 bit integer samples, because they are converted to 32 bit floats (I assume this is an ok design decision)

Here's full test results (many fail because 8-bit samples and compressed files are not supported, so the result is actually quite ok):

    Testing command: tools/pacmog-rs-tester/target/debug/pacmog-rs-tester
    OK  : tests/aifc/aifc-channels-2-fl32.aifc
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-channels-4.aifc
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-chunk-fllr.aifc
    - process returned non-zero exit status: 255
    FAIL: tests/aifc/aifc-chunk-ssnd-before-comm-fver.aifc
    - values differ for "sampleRate", got: '0', expected: '44100'
    - values differ for "channels", got: '0', expected: '1'
    - unsupported: codec
    - values differ for "sampleSize", got: '0', expected: '8'
    - values differ for "samplesPerChannel", got: '0', expected: '4411'
    - values differ for "startSamples", channel 0, index 0, got: 0, expected: 10
    - values differ for "endSamples", channel 0, index 0, got: 0, expected: 33
    thread 'main' panicked at 'assertion failed: `(left != right)`
      left: `0`,
    right: `0`', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/lib.rs:100:13
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aifc/aifc-chunk-unknown-size-zero.aifc
    - process returned non-zero exit status: 101
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-chunk-unknown.aifc
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-samplerate-8912.75.aifc
    - process returned non-zero exit status: 255
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aifc/aifc-type-23ni.aifc
    - process returned non-zero exit status: 101
    OK  : tests/aifc/aifc-type-fl32-nan-inf.aifc
    OK  : tests/aifc/aifc-type-fl32-uppercase.aifc
    OK  : tests/aifc/aifc-type-fl32-wide-range.aifc
    OK  : tests/aifc/aifc-type-fl32.aifc
    OK  : tests/aifc/aifc-type-fl64-nan-inf.aifc
    OK  : tests/aifc/aifc-type-fl64-uppercase.aifc
    OK  : tests/aifc/aifc-type-fl64-wide-range.aifc
    OK  : tests/aifc/aifc-type-fl64.aifc
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aifc/aifc-type-in24.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aifc/aifc-type-in32.aifc
    - process returned non-zero exit status: 101
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-type-none-samplesize-12.aifc
    - process returned non-zero exit status: 255
    OK  : tests/aifc/aifc-type-none-samplesize-16.aifc
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-type-none-samplesize-23.aifc
    - process returned non-zero exit status: 255
    OK  : tests/aifc/aifc-type-none-samplesize-24.aifc
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-type-none-samplesize-31.aifc
    - process returned non-zero exit status: 255
    FAIL: tests/aifc/aifc-type-none-samplesize-32.aifc
    - values differ for "startSamples", channel 0, index 9, got: -2104631424.0, expected: -2104631367
    - values differ for "endSamples", channel 0, index 0, got: 519096960.0, expected: 519096953
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-type-none-samplesize-5.aifc
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aifc/aifc-type-none-samplesize-8.aifc
    - process returned non-zero exit status: 255
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aifc/aifc-type-raw-u8.aifc
    - process returned non-zero exit status: 101
    OK  : tests/aifc/aifc-type-sowt.aifc
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aifc/aifc-type-twos.aifc
    - process returned non-zero exit status: 101
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-channels-1.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-channels-10.aiff
    - process returned non-zero exit status: 255
    OK  : tests/aiff/aiff-channels-2-bei16.aiff
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-channels-2.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-channels-4.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-aesd.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-anno-two.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-anno.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-appl.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-auth.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-chan.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-comments-one.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-comments-ref-marker.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-comments-two.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-comments-zero.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-copy.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-fllr.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-hash.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-inst.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-markers-zero.aiff
    - process returned non-zero exit status: 255
    FAIL: tests/aiff/aiff-chunk-markers.aiff
    - unsupported: markers
    - values differ for "startSamples", channel 0, index 17, got: -2104631424.0, expected: -2104631367
    - values differ for "startSamples", channel 1, index 25, got: -2104631424.0, expected: -2104631367
    - values differ for "endSamples", channel 0, index 0, got: 176278704.0, expected: 176278702
    - values differ for "endSamples", channel 1, index 0, got: -166539552.0, expected: -166539549
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-midi.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-name.aiff
    - process returned non-zero exit status: 255
    FAIL: tests/aiff/aiff-chunk-ssnd-before-comm.aiff
    - values differ for "sampleRate", got: '0', expected: '44100'
    - values differ for "channels", got: '0', expected: '1'
    - unsupported: codec
    - values differ for "sampleSize", got: '0', expected: '8'
    - values differ for "samplesPerChannel", got: '0', expected: '4411'
    - values differ for "startSamples", channel 0, index 0, got: 0, expected: 10
    - values differ for "endSamples", channel 0, index 0, got: 0, expected: 33
    thread 'main' panicked at 'assertion failed: `(left == right)`
      left: `170`,
    right: `0`', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/lib.rs:109:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aiff/aiff-chunk-ssnd-blocksize.aiff
    - process returned non-zero exit status: 101
    OK  : tests/aiff/aiff-chunk-ssnd-missing.aiff
    thread 'main' panicked at 'assertion failed: `(left == right)`
      left: `8192`,
    right: `0`', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/lib.rs:108:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aiff/aiff-chunk-ssnd-offset-blocksize.aiff
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'assertion failed: `(left == right)`
      left: `8192`,
    right: `0`', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/lib.rs:108:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/aiff/aiff-chunk-ssnd-offset.aiff
    - process returned non-zero exit status: 101
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-chunk-ssnd-samples-one.aiff
    - process returned non-zero exit status: 255
    OK  : tests/aiff/aiff-chunk-ssnd-samples-zero.aiff
    FAIL: tests/aiff/aiff-chunk-ssnd-vs-sampleframes.aiff
    - values differ for "samplesPerChannel", got: '4411', expected: '12603'
    - values differ for "endSamples", channel 0, index 0, got: 8575.0, expected: 8481
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplerate-0.01.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplerate-1.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplerate-11025.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplerate-22050.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplerate-2900000.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplerate-384000.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplerate-44100.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplerate-5298.25.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplesize-1.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplesize-12.aiff
    - process returned non-zero exit status: 255
    OK  : tests/aiff/aiff-samplesize-16.aiff
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplesize-20.aiff
    - process returned non-zero exit status: 255
    OK  : tests/aiff/aiff-samplesize-24.aiff
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplesize-29.aiff
    - process returned non-zero exit status: 255
    FAIL: tests/aiff/aiff-samplesize-32.aiff
    - values differ for "startSamples", channel 0, index 9, got: -2104631424.0, expected: -2104631425
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplesize-4.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/aiff/aiff-samplesize-8.aiff
    - process returned non-zero exit status: 255
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-agsm.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-alaw-uppercase.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-alaw.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-dwvw-16bit.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-dwvw-24bit.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-g722.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-ima4.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-mac3-ch2.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-mac3.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-mac6.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-qclp.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-qdm2.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-qdmc.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-ulaw-ch2.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-ulaw-uppercase.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/compressed/compressed-ulaw.aifc
    - process returned non-zero exit status: 101
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/exported/audacity-i8-id3.aiff
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/exported/audacity-i8.aiff
    - process returned non-zero exit status: 255
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/exported/audacity-ima-adpcm.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'assertion failed: `(left == right)`
      left: `2280`,
    right: `0`', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/lib.rs:108:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/exported/finder-codec-sowt.aifc
    - process returned non-zero exit status: 101
    OK  : tests/exported/garageband-16-bit.aiff
    - unsupported: markers
    - unsupported: comments
    - unsupported: chan
    OK  : tests/exported/garageband-24-bit.aiff
    - unsupported: markers
    - unsupported: comments
    - unsupported: chan
    OK  : tests/exported/garageband-cyclemarker.aiff
    - unsupported: markers
    - unsupported: comments
    - unsupported: chan
    OK  : tests/exported/imovie.aiff
    - unsupported: chan
    OK  : tests/exported/itunes-16bit-stereo.aiff
    - unsupported: id3
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/exported/itunes-8bit-mono.aiff
    - process returned non-zero exit status: 255
    OK  : tests/exported/motion.aifc
    - unsupported: chan
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/exported/python3-alaw.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/exported/python3-ulaw.aifc
    - process returned non-zero exit status: 101
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/exported/quicktime5-alaw.aifc
    - process returned non-zero exit status: 101
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/exported/quicktime5-fl32.aifc
    - process returned non-zero exit status: 255
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/exported/quicktime5-fl64.aifc
    - process returned non-zero exit status: 255
    OK  : tests/exported/quicktime5-samplesize-16.aiff
    OK  : tests/exported/quicktime5-samplesize-24.aiff
    FAIL: tests/exported/quicktime5-samplesize-32.aiff
    - values differ for "startSamples", channel 0, index 9, got: -2104655232.0, expected: -2104655219
    - values differ for "endSamples", channel 0, index 0, got: 519053056.0, expected: 519053040
    * ERROR: PcmReader::read_sample() failed: Unsupported bit-depth
    FAIL: tests/exported/quicktime5-samplesize-8.aiff
    - process returned non-zero exit status: 255
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/kari/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pacmog-0.4.1/src/aiff.rs:140:85
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    FAIL: tests/exported/quicktime5-ulaw.aifc
    - process returned non-zero exit status: 101
    Total 114: 25 passed, 89 failed.

For comparison, here's [macOS AudioToolbox results](https://github.com/karip/toisto-aiff-test-suite/blob/main/result-audiotoolbox-tester.md).

You can run the test suite yourself by building the tester code and running the test suite like this (requires python3):

 - copy the source code for [the tester](https://gist.github.com/karip/55966b46539589327249f894759d0892) to your local computer as `pacmog-rs-tester.rs`
 - install [cargo-single](https://crates.io/crates/cargo-single) `cargo install cargo-single` (or you can create a project for the tester yourself)
 - compile the tester: `cargo single run pacmog-rs-tester.rs`
 - clone the test suite and run it:
~~~~
    git clone https://github.com/karip/toisto-aiff-test-suite.git
    cd toisto-aiff-test-suite
    python3 runner.py path-to-tester/pacmog-rs-tester/target/debug/pacmog-rs-tester
~~~~

**Comment by AkiyukiOkayasu** [comment]
I have not tested AIFF enough, so your report is very helpful.
I agree with you that an unsupported compression type input should not cause panic.
This needs to be fixed in the next version.

I didn't dare to support 8bit samples.
Because in many cases IMA-ADPCM is better in terms of sound quality.
If a perfect AIFF decoder is the goal, it should be supported, but I have no plans to support it in the future, because I have decided that pacmog is good enough to work for embedded applications.

Anyway, thank you for your detailed report, it is much appreciated.

**Comment by karip** [comment]
It's ok if you don't want to support 8-bit samples. Does AIFF support IMA-ADPCM?

I noticed that you opened separate issues for the bugs. I opened few more issues about missing formats. Thank you for creating pacmog! It has given me some ideas how to improve my test suite.
