### ISSUE TITLE
Big endian AIFF decoding issue

### ISSUE THREAD

**Issue by AkiyukiOkayasu** [AkiyukiOkayasu/pacmog#35]
https://github.com/AkiyukiOkayasu/pacmog/issues/33#issue-1881708527
> it doesn't support uncompressed type "TWOS" in AIFC files (16-bit big-endian signed integer samples)

**Comment by karip** [comment]
Here's a zip file containing aiff-c with compression type 'twos' (uncompressed 16-bit big-endian signed integer)

[aifc-type-twos.aifc.zip](https://github.com/AkiyukiOkayasu/pacmog/files/12594428/aifc-type-twos.aifc.zip)
